ALTER TABLE vacancies DROP COLUMN IF EXISTS lng;
ALTER TABLE vacancies DROP COLUMN IF EXISTS lat;
ALTER TABLE users DROP COLUMN IF EXISTS referrer_at;
ALTER TABLE users DROP COLUMN IF EXISTS referrer_id;
ALTER TABLE companies DROP COLUMN IF EXISTS bot_username;
ALTER TABLE companies DROP COLUMN IF EXISTS bot_user_id;
