ALTER TABLE companies ADD COLUMN bot_user_id BIGINT;
ALTER TABLE companies ADD COLUMN bot_username TEXT NOT NULL DEFAULT '';

ALTER TABLE users ADD COLUMN referrer_id BIGINT REFERENCES users (id);
ALTER TABLE users ADD COLUMN referrer_at TIMESTAMPTZ;

ALTER TABLE vacancies ADD COLUMN lat DOUBLE PRECISION;
ALTER TABLE vacancies ADD COLUMN lng DOUBLE PRECISION;
